### ISSUE TITLE
ES6 distribution and `module` in `package.json`

### ISSUE THREAD

**Issue by brettz9** [atomiks/tippyjs#270]
From https://github.com/atomiks/tippyjs/blob/master/scripts/build.js#L73 , it looks like an ES6 Module build was envisioned, but the config is not actually written to file there.

For those taking advantage of ES6 modules (without the need for plugins to convert from UMD), could you include that ES6 Module distribution and reference that file in `package.json` via the `module` property?

See e.g., https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

Thanks!

**Comment by atomiks** [comment]
Sorry for not responding 🙏

V2 is only getting bugfixes now, all features are going to V3 which is tagged `tippy.js@next`. 

I've just released `3.0.0-alpha.1` with an `esm` directory and module field linking to `dist/esm/tippy.js`. 

Hope that helps 😄

**Comment by brettz9** [comment]
Awesome, thanks!

FWIW though, it looks like you have an older tag for "3.0.0-alpha.1" which doesn't contain the changes in your "3.0.0-alpha.1" commit.

**Comment by brettz9** [comment]
I'm able to import now, thanks, but the functionality I'm using of v3.0.0-alpha.3--whether as a module or not--is not working as it is in v2. Maybe it's because my tooltip is inside a table, or maybe it's because your alpha is a rough one, but thought I'd mention it in case this is unexpected and I should report an issue.

**Comment by atomiks** [comment]
v3 has breaking changes, you read about them here: https://github.com/atomiks/tippyjs/releases/tag/v3.0.0-alpha.0

**Comment by brettz9** [comment]
Ok, thanks, that helped, but I'm still not seeing the default black background-white text style be applied to the tooltips even though the tooltips are showing.... I've switched to `data-tippy-content` and other dynamic settings are getting applied, but with or without the settings, the default styles aren't applying and I didn't see any breaking changes regarding colors/styling...

**Comment by atomiks** [comment]
You need to import the CSS yourself as well. The module only has the JS.

**Comment by brettz9** [comment]
I'm not sure when this happened, but this statement is showing up in your dist ESM build:

```js
import Popper from 'popper.js';
```

I guess this is either a module you meant to have Rollup bundle or you are trying to import from a file also supposed to be in `dist` with that file, in which case you'd need "./" right before "popper.js". But it won't work from the browser currently as is without that getting transformed somehow...

**Comment by brettz9** [comment]
Looks like it already broke at beta 0... I'll go ahead and reopen then if that's ok..

**Comment by atomiks** [comment]
You need Popper.js as well. It's a dependency

**Comment by brettz9** [comment]
Hmm... I do see the non-standalone version is working, but the `module`-pointed `dist` file is supposed to work as is without need for bundling... And again, unless it is Node, it won't work in the browser to import other files without "./" (or such--not a path like "tippy.js" without the dot-slash or dot-dot-slash, etc.) resolving to an actual path (unless the user is required to do their own bundling which is discouraged). I think this was to distinguish it from module resolution such as Node has (in case perhaps the browser ever supports some module resolution).

**Comment by atomiks** [comment]
Well most people use a build tool to bundle modules instead of using them directly in a browser because of browser support and reasons like this. The import as it currently is is more useful because the latest Popper@1 version is used if the bundle is outdated (it almost never is, but yeah).

Why not just use the UMD version for the browser? As it stands ESM is purely for module bundlers like webpack/Parcel

**Comment by brettz9** [comment]
ESM is also for the browser if you don't care about old browser support--ESM works directly in Firefox, Chrome, Safari, etc. (not IE11 or a lot of mobile: https://caniuse.com/#feat=es6-module )--for some projects I'm working on, I don't. And I very much prefer to express code modularly without myself (or fellow coders) needing to track dependencies beyond the JS file which is doing the importing...

But as mentioned, I do see your `/esm/tippy.js file` is working for me for my needs at the moment, so I'm happy!
